import { NextRequest, NextResponse } from "next/server";
import { audit, database, getActor, makeId } from "@/lib/server";

export async function PATCH(req: NextRequest,{params}:{params:Promise<{id:string}>}) { const actor=await getActor("/applications"); if(!["ADMIN","MANAGER","TEACHER"].includes(actor.role)) return NextResponse.json({error:"Недостаточно прав"},{status:403}); const {id}=await params; const body=await req.json() as Record<string, any>; const db=database(); const now=new Date().toISOString();
  const application=await db.prepare("SELECT person_id FROM applications WHERE id=?").bind(id).first<{person_id:string}>();if(!application)return NextResponse.json({error:"Кандидат не найден"},{status:404});
  if(body.profile&&actor.role!=="TEACHER"){const p=body.profile as Record<string,unknown>;await db.prepare("UPDATE people SET full_name=?,email=?,phone=?,birth_date=?,city=?,region=?,education=?,employment_status=?,it_experience=?,regional=? WHERE id=?").bind(String(p.fullName??"").trim(),String(p.email??"").trim().toLowerCase()||null,String(p.phone??"").trim()||null,String(p.birthDate??"")||null,String(p.city??"").trim()||null,String(p.region??"").trim()||null,String(p.education??"").trim()||null,String(p.employmentStatus??"").trim()||null,String(p.itExperience??"").trim()||null,p.regional?1:0,application.person_id).run();}
  if(body.application&&actor.role!=="TEACHER"){
    const a=body.application as Record<string,unknown>;
    const courseId=["junior-frontend","middle-frontend"].includes(String(a.courseId))?String(a.courseId):null;
    const workflowStatus=["NEW","IN_REVIEW","APPROVED","REJECTED"].includes(String(a.status))?String(a.status):null;
    if(courseId){
      const duplicate=await db.prepare("SELECT id FROM applications WHERE person_id=? AND cycle_id=(SELECT cycle_id FROM applications WHERE id=?) AND course_id=? AND id<>?").bind(application.person_id,id,courseId,id).first();
      if(duplicate)return NextResponse.json({error:"У кандидата уже есть заявка на это направление"},{status:409});
    }
    await db.prepare("UPDATE applications SET course_id=COALESCE(?,course_id),status=COALESCE(?,status),cv_url=?,notes=?,learning_goal=?,updated_at=? WHERE id=?").bind(courseId,workflowStatus,String(a.cvUrl??"").trim()||null,String(a.notes??"").trim()||null,String(a.learningGoal??"").trim()||null,now,id).run();
  }
  if(body.cvStatus&&["NOT_REVIEWED","APPROVED","MAYBE","REJECTED"].includes(body.cvStatus)){ await db.batch([db.prepare("UPDATE applications SET cv_status=?,status='IN_REVIEW',updated_at=? WHERE id=?").bind(body.cvStatus,now,id),db.prepare("INSERT INTO cv_reviews (id,application_id,decision,comment,reviewer_id,created_at) VALUES (?,?,?,?,?,?)").bind(makeId("cv"),id,body.cvStatus,body.cvComment||null,actor.id,now)]); }
  if(body.motivationStatus&&actor.role!=="TEACHER"&&["NOT_SENT","SENT","RECEIVED","REJECTED"].includes(body.motivationStatus))await db.prepare("UPDATE applications SET motivation_status=?,updated_at=? WHERE id=?").bind(body.motivationStatus,now,id).run();
  if(body.interviewStatus&&actor.role!=="TEACHER"&&["NOT_SCHEDULED","SCHEDULED","ATTENDED","NO_SHOW"].includes(body.interviewStatus)){ await db.prepare("UPDATE applications SET interview_status=?,updated_at=? WHERE id=?").bind(body.interviewStatus,now,id).run(); await db.prepare("INSERT INTO interviews (id,application_id,scheduled_at,calendly_url,attendance,decision,comment,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(application_id) DO UPDATE SET scheduled_at=excluded.scheduled_at,calendly_url=excluded.calendly_url,attendance=excluded.attendance,decision=excluded.decision,comment=excluded.comment,updated_at=excluded.updated_at").bind(makeId("int"),id,body.scheduledAt||null,body.calendlyUrl||null,body.interviewStatus==="ATTENDED"?"ATTENDED":body.interviewStatus==="NO_SHOW"?"NO_SHOW":"UNKNOWN",body.interviewDecision||"PENDING",body.interviewComment||null,now).run(); }
  if(body.finalDecision&&actor.role!=="TEACHER"&&["PENDING","ACCEPTED","REJECTED","WAITLIST"].includes(body.finalDecision)){const overall=body.finalDecision==="ACCEPTED"?"APPROVED":body.finalDecision==="REJECTED"?"REJECTED":"IN_REVIEW";await db.prepare("UPDATE applications SET final_decision=?,status=?,updated_at=? WHERE id=?").bind(body.finalDecision,overall,now,id).run(); }
  await audit(actor.id,"UPDATE_APPLICATION","application",id,body); return NextResponse.json({ok:true}); }
