"use client";
import Link from "next/link";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";

export function ApplicationTable({ rows }: { rows: Array<Record<string, any>> }) {
  const copyEmails = async () => { await navigator.clipboard.writeText(rows.map(r=>r.email).filter(Boolean).join(", ")); };
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-4"><p className="text-sm text-slate-500">Найдено: <strong className="text-slate-900">{rows.length}</strong></p><Button variant="outline" size="sm" onClick={copyEmails} disabled={!rows.length}>Скопировать email</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Кандидат</th><th className="px-4 py-3">Курс</th><th className="px-4 py-3">Регион</th><th className="px-4 py-3">CV</th><th className="px-4 py-3">Мотивация</th><th className="px-4 py-3">Интервью</th><th className="px-4 py-3">Решение</th><th className="px-4 py-3">Действия</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3"><Link href={`/applications/${row.id}`} className="font-semibold text-blue-900 hover:underline">{row.full_name}</Link><p className="mt-1 text-xs text-slate-500">{row.application_number?`№ ${row.application_number} · `:""}{row.email ?? row.phone ?? row.iin ?? "—"}</p></td><td className="px-4 py-3">{row.course_name}</td><td className="px-4 py-3">{row.region ?? "—"}{row.regional ? <p className="text-xs font-semibold text-blue-700">Региональная квота</p>:null}</td><td className="px-4 py-3"><StatusBadge value={row.cv_status}/></td><td className="px-4 py-3"><StatusBadge value={row.motivation_status}/></td><td className="px-4 py-3"><StatusBadge value={row.interview_status}/></td><td className="px-4 py-3"><StatusBadge value={row.final_decision}/></td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/applications/${row.id}`} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold hover:bg-slate-50">Карточка</Link>{row.cv_url&&<Link href={`/applications/${row.id}#cv`} className="rounded-lg bg-blue-50 px-2.5 py-1.5 text-xs font-semibold text-blue-800 hover:bg-blue-100">CV</Link>}</div></td></tr>)}</tbody></table></div>{!rows.length && <div className="p-12 text-center text-sm text-slate-500">Кандидаты по выбранным условиям не найдены.</div>}</div>;
}
