"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

export function CandidateActions({ id, current, canManage=true }: { id: string; current: Record<string, any>; canManage?:boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [comment, setComment] = useState("");
  async function update(payload: Record<string, unknown>) {
    setBusy(true);
    try {
      const r = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
      const json = await r.json() as Record<string, any>;
      if (!r.ok) throw new Error(json.error ?? "Ошибка");
      toast.success("Изменения сохранены"); setComment(""); router.refresh();
    } catch (error) { toast.error(error instanceof Error ? error.message : "Ошибка"); } finally { setBusy(false); }
  }
  function value(id:string){return (document.getElementById(id) as HTMLInputElement|HTMLTextAreaElement)?.value??""}
  return <div className="space-y-5">
    {canManage&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Данные кандидата</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">
      <label className="text-sm font-semibold">ФИО<input id="profileName" defaultValue={current.full_name??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Email<input id="profileEmail" type="email" defaultValue={current.email??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Телефон<input id="profilePhone" defaultValue={current.phone??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Дата рождения<input id="profileBirthDate" type="date" defaultValue={current.birth_date??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Регион<input id="profileRegion" defaultValue={current.region??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Город<input id="profileCity" defaultValue={current.city??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Образование<input id="profileEducation" defaultValue={current.education??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Занятость<input id="profileEmployment" defaultValue={current.employment_status??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold">Опыт в IT<input id="profileExperience" defaultValue={current.it_experience??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="flex items-center gap-2 self-end rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold"><input id="profileRegional" type="checkbox" defaultChecked={Boolean(current.regional)}/>Региональная квота</label>
      <label className="text-sm font-semibold">Направление<select id="applicationCourse" defaultValue={current.course_id} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"><option value="junior-frontend">Junior Frontend Developer</option><option value="middle-frontend">Middle Frontend Engineer</option></select></label>
      <label className="text-sm font-semibold">Этап заявки<select id="applicationStatus" defaultValue={current.status} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"><option value="NEW">Новая</option><option value="IN_REVIEW">В работе</option><option value="APPROVED">Одобрена</option><option value="REJECTED">Отклонена</option></select></label>
      <label className="text-sm font-semibold sm:col-span-2">Ссылка на CV<input id="applicationCvUrl" defaultValue={current.cv_url??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label>
      <label className="text-sm font-semibold sm:col-span-2">Цель обучения<textarea id="applicationGoal" defaultValue={current.learning_goal??""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>
      <label className="text-sm font-semibold sm:col-span-2">Внутренняя заметка<textarea id="applicationNotes" defaultValue={current.notes??""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>
    </div><Button className="mt-4" disabled={busy} onClick={()=>update({profile:{fullName:value("profileName"),email:value("profileEmail"),phone:value("profilePhone"),birthDate:value("profileBirthDate"),region:value("profileRegion"),city:value("profileCity"),education:value("profileEducation"),employmentStatus:value("profileEmployment"),itExperience:value("profileExperience"),regional:(document.getElementById("profileRegional") as HTMLInputElement).checked},application:{courseId:value("applicationCourse"),status:value("applicationStatus"),cvUrl:value("applicationCvUrl"),learningGoal:value("applicationGoal"),notes:value("applicationNotes")}})}>Сохранить данные</Button></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Проверка CV</h2><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Комментарий преподавателя" className="mt-3 min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>update({cvStatus:"APPROVED",cvComment:comment})}>Одобрить</Button><Button disabled={busy} variant="outline" onClick={()=>update({cvStatus:"MAYBE",cvComment:comment})}>В резерв</Button><Button disabled={busy} variant="destructive" onClick={()=>update({cvStatus:"REJECTED",cvComment:comment})}>Отклонить</Button></div></section>
    {canManage&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Мотивационное письмо</h2><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>update({motivationStatus:"RECEIVED"})}>Получено</Button><Button variant="outline" disabled={busy} onClick={()=>update({motivationStatus:"SENT"})}>Запрошено</Button><Button variant="ghost" disabled={busy} onClick={()=>update({motivationStatus:"NOT_SENT"})}>Не получено</Button></div></section>}
    {canManage&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Интервью и финальное решение</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Дата и время<input id="scheduledAt" type="datetime-local" defaultValue={current.scheduled_at?.slice(0,16)??""} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label><label className="text-sm font-semibold">Персональная ссылка Calendly<input id="calendlyUrl" defaultValue={current.calendly_url??""} placeholder="оставьте пустым до назначения" className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal"/></label><label className="text-sm font-semibold sm:col-span-2">Комментарий по интервью<textarea id="interviewComment" defaultValue={current.comment??""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>update({interviewStatus:"SCHEDULED",scheduledAt:value("scheduledAt")||null,calendlyUrl:value("calendlyUrl")||null,interviewComment:value("interviewComment")})}>Назначить</Button><Button variant="outline" disabled={busy} onClick={()=>update({interviewStatus:"ATTENDED",scheduledAt:value("scheduledAt")||null,calendlyUrl:value("calendlyUrl")||null,interviewComment:value("interviewComment")})}>Проведено</Button><Button variant="outline" disabled={busy} onClick={()=>update({interviewStatus:"NO_SHOW",scheduledAt:value("scheduledAt")||null,calendlyUrl:value("calendlyUrl")||null,interviewComment:value("interviewComment")})}>Не пришёл</Button></div><div className="mt-4 border-t border-slate-100 pt-4"><p className="mb-3 text-sm font-semibold">Финальное решение</p><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>update({finalDecision:"ACCEPTED"})}>Принять</Button><Button variant="outline" disabled={busy} onClick={()=>update({finalDecision:"WAITLIST"})}>Резерв</Button><Button variant="destructive" disabled={busy} onClick={()=>update({finalDecision:"REJECTED"})}>Отказать</Button><Button variant="ghost" disabled={busy} onClick={()=>update({finalDecision:"PENDING"})}>Сбросить решение</Button></div></div></section>}
  </div>;
}
