"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

export function ImportPanel() {
  const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Record<string,any>|null>(null);
  async function upload(){if(!file)return;setBusy(true);try{const form=new FormData();form.append("file",file);const r=await fetch("/api/import",{method:"POST",body:form});const json=await r.json() as Record<string,any>;if(!r.ok)throw new Error(json.error||"Ошибка импорта");setResult(json);toast.success("Импорт завершён")}catch(error){toast.error(error instanceof Error?error.message:"Ошибка")}finally{setBusy(false)}}
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-10 text-center hover:border-blue-400 hover:bg-blue-50/40"><input type="file" accept=".xls,.xlsx,.csv" className="sr-only" onChange={e=>setFile(e.target.files?.[0]??null)}/><span className="inline-flex rounded-xl bg-[#172554] px-4 py-2.5 font-semibold text-white">{file?"Выбрать другой файл":"Выбрать файл"}</span>{file&&<span className="mt-3 block font-semibold text-blue-900">{file.name}</span>}<span className="mt-2 block text-sm text-slate-500">Поддерживаются .xls, .xlsx и .csv</span></label><div className="mt-4 flex items-center gap-3"><Button disabled={!file||busy} onClick={upload}>{busy?"Импортируем…":"Запустить импорт"}</Button>{!file&&<span className="text-sm text-slate-500">Сначала выберите файл выше</span>}</div>{result&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-2xl font-bold">{result.total}</p><p className="text-xs text-slate-500">строк</p></div><div className="rounded-xl bg-emerald-50 p-4"><p className="text-2xl font-bold text-emerald-700">{result.imported}</p><p className="text-xs text-emerald-700">импортировано</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-2xl font-bold text-amber-700">{result.skipped}</p><p className="text-xs text-amber-700">пропущено</p></div>{result.issues?.length>0&&<details className="sm:col-span-3"><summary className="cursor-pointer text-sm font-semibold text-amber-700">Показать ошибки ({result.issues.length})</summary><ul className="mt-2 space-y-1 text-sm text-slate-600">{result.issues.slice(0,30).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></details>}</div>}</div>;
}
