"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

export function NewCandidateForm(){
  const router=useRouter();const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);try{const r=await fetch("/api/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const data=await r.json() as Record<string,string>;if(!r.ok)throw new Error(data.error||"Ошибка");toast.success("Кандидат добавлен");router.push(`/applications/${data.id}`)}catch(error){toast.error(error instanceof Error?error.message:"Ошибка")}finally{setBusy(false)}}
  return <details className="rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer p-4 text-sm font-semibold text-blue-800">+ Добавить кандидата вручную</summary><form onSubmit={submit} className="grid gap-3 border-t border-slate-100 p-4 sm:grid-cols-2 xl:grid-cols-4"><input name="fullName" required placeholder="ФИО *" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="iin" placeholder="ИИН" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="email" type="email" placeholder="Email" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="phone" placeholder="Телефон" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><select name="course" required className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Выберите курс *</option><option value="junior-frontend">Junior Frontend</option><option value="middle-frontend">Middle Frontend</option></select><input name="region" placeholder="Регион" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="city" placeholder="Город" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="cvUrl" placeholder="Ссылка на CV" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><label className="flex items-center gap-2 text-sm"><input name="regional" type="checkbox" value="true"/>Региональная квота</label><div className="sm:col-span-2 xl:col-span-3"><Button type="submit" disabled={busy}>{busy?"Добавляем…":"Добавить"}</Button></div></form></details>
}
