import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { CandidateActions } from "@/components/candidate-actions";
import { StatusBadge } from "@/components/status-badge";
import { applicationDetail, getActor } from "@/lib/server";

export const dynamic="force-dynamic";
export default async function CandidatePage({params}:{params:Promise<{id:string}>}) { const {id}=await params; const actor=await getActor(`/applications/${id}`); const data=await applicationDetail(id); if(!data) notFound(); const a=data.application as Record<string,any>; const interview=(data.interview??{}) as Record<string,any>;
  return <AppShell actor={actor}><div className="space-y-5"><div><Link href="/applications" className="text-sm font-semibold text-blue-700">← Кандидаты</Link><div className="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold tracking-tight">{a.full_name}</h1><p className="mt-2 text-sm text-slate-500">{a.course_name}</p></div><div className="flex items-center gap-3">{a.cv_url&&<a href="#cv" className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold">Посмотреть CV</a>}<StatusBadge value={a.final_decision}/></div></div></div><div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Данные кандидата</h2><dl className="mt-4 space-y-3 text-sm">{[["Email",a.email],["Телефон",a.phone],["ИИН",a.iin],["Дата рождения",a.birth_date],["Город",a.city],["Регион",a.region],["Образование",a.education],["Занятость",a.employment_status],["Опыт в IT",a.it_experience],["Региональная квота",a.regional?"Да":"Нет"]].map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-0.5 font-medium">{v??"—"}</dd></div>)}</dl></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Этапы</h2><div className="mt-4 space-y-3 text-sm">{[["CV",a.cv_status],["Мотивация",a.motivation_status],["Интервью",a.interview_status],["Решение",a.final_decision]].map(([k,v])=><div key={k} className="flex items-center justify-between gap-3"><span>{k}</span><StatusBadge value={v}/></div>)}</div></section></div><CandidateActions id={id} current={{...a,...interview}} canManage={actor.role!=="TEACHER"}/></div>{a.cv_url&&<section id="cv" className="scroll-mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-4"><div><h2 className="font-bold">CV кандидата</h2><p className="text-xs text-slate-500">Просмотр без скачивания</p></div><a href={a.cv_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold">Скачать оригинал</a></div><iframe title={`CV — ${a.full_name}`} src={`/api/cv/${id}`} className="h-[720px] w-full bg-slate-100"/></section>}{data.reviews.length>0&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">История проверок CV</h2><div className="mt-3 divide-y divide-slate-100">{(data.reviews as Array<Record<string,any>>).map(r=><div key={r.id} className="py-3 text-sm"><div className="flex items-center justify-between"><StatusBadge value={r.decision}/><span className="text-xs text-slate-400">{new Date(r.created_at).toLocaleString("ru-RU")}</span></div>{r.comment&&<p className="mt-2 text-slate-600">{r.comment}</p>}</div>)}</div></section>}</div></AppShell>;
}
